# Data config
numeric_features: ["gps_lat", "gps_lon", "screen_state", "energy", "danceability"]
categorical_features: ["location_type", "app_category"]
target_column: "valence"

# Model config
transformer:
  max_seq_len:
  d_model:
  input_dim:
  dropout:
  nhead:
  num_layers:
  output_dim:
  learning_rate: 1e-3

gnn:
  input_dim:
  hidden_dim: 
  output_dim:
  num_layers:
  dropout:
  learning_rate: 1e-3

# Logging config
wandb:
  project: "music_prediction"
  entity: "your_wandb_team"

elastic_net:
  max_iter: 10000
  alpha_range:
  l1_ratio_range: 
  random_state: 42

random_forest:
  n_estimators: 200
  max_features: "sqrt"
  min_samples_leaf: 20
  random_state: 42

neural_net:
  input_dim: 32
  hidden_dims:
  output_dim: 1 
  dropout: 0.1
  learning_rate: 1e-3

dataset:
  batch_size: 32
  num_workers: 4
  drop_features: ["timestamp"]  # Examples for all, drop here all Punctuation features from LUKE
  numeric_features: ["gps_lat", "gps_lon", "screen_state", "energy", "danceability"]
  categorical_features: ["location_type", "app_category"]
  binary_features: []
  pass_through_features: []